version: '3'

services:
  mysql:
    image: mysql:8.0.26
    container_name: mysql
    restart: on-failure
    environment:
      - TZ=Asia/Seoul
      - MYSQL_DATABASE=matching
      - MYSQL_ROOT_PASSWORD=madmin
    ports:
      - 3306:3306
    networks:
      - match-network
    volumes: 
      - ./mysql/init/:/docker-entrypoint-initdb.d/

networks:
  match-network:

volumes:
  postgres: {}