version: '3'

services:
  spring:
    build: ./backend
    container_name: spring
    networks:
      - match-network
    depends_on:
      - mysql
      - redis
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/matching
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=madmin
  mysql:
    image: mysql:8.0.26
    container_name: mysql
    restart: on-failure
    environment:
      - TZ=Asia/Seoul
      - MYSQL_DATABASE=matching
      - MYSQL_ROOT_PASSWORD=madmin
    ports:
      - 3306:3306
    networks:
      - match-network
    command:
      - --character-set-server=utf8 
      - --collation-server=utf8_general_ci
    volumes: 
      - ./mysql/init/:/docker-entrypoint-initdb.d/
  frontend:
    container_name: frontend
    build: ./vue
    ports:
      - "80:80"
      - "443:443"
    networks:
      - match-network
    restart: always
    user: root
    depends_on:
      - spring

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    environment:
      - TZ=Asia/Seoul
    networks:
      - match-network


networks:
  match-network:

volumes:
  postgres: {}
  redis: {}
