const techStacks = [
  'c',
  'd',
  'qt',
  'c#',
  'go',
  'f#',
  'om',
  'zk',
  'db',
  'cq',
  'm3',
  'zio',
  'bem',
  'lit',
  'ios',
  'wsl',
  'pwa',
  'qt5',
  'sdl',
  'eel',
  'fbs',
  'koa',
  'hug',
  'ent',
  'pug',
  'ejs',
  'php',
  'es6',
  'c++',
  'lua',
  'elm',
  'xml',
  'awk',
  'jsx',
  'nim',
  'arc',
  'red',
  'bel',
  'ada',
  'cue',
  'eve',
  'eta',
  'emu',
  'jsf',
  'gwt',
  'fzf',
  'jsf',
  'cdi',
  'swt',
  'yii',
  'ihp',
  'lad',
  'nsq',
  'wcf',
  'emq',
  'xap',
  'pig',
  'hue',
  'bds',
  'kue',
  'que',
  'dbt',
  'dat',
  'awx',
  'rex',
  'geb',
  '1mb',
  'nix',
  'fpm',
  'hex',
  'git',
  'dvc',
  'goa',
  'vim',
  'kvm',
  'xen',
  'azk',
  'npm',
  'pip',
  'duo',
  'sbt',
  'fly',
  'bfe',
  'hub',
  'mou',
  'act',
  'oni',
  'id3',
  'moq',
  'k3s',
  'k9s',
  'jib',
  'k0s',
  'k3d',
  'gor',
  'ace',
  'pmd',
  'ava',
  'fpm',
  'lxc',
  'lxd',
  'rkt',
  'bit',
  'seq',
  'uno',
  'zap',
  'elk',
  'spm',
  '411',
  'pm2',
  'ggez',
  'akka',
  'rxjs',
  'avro',
  'dojo',
  'kube',
  'pure',
  'susy',
  'miso',
  'wine',
  'onos',
  'expo',
  'pyqt',
  'ribs',
  'juce',
  'juce',
  'qbrt',
  'hapi',
  'slim',
  'echo',
  'ktor',
  'iron',
  'twig',
  'haxe',
  'dust',
  'java',
  'ruby',
  'rust',
  'dart',
  'perl',
  'json',
  'haml',
  'yaml',
  'ceph',
  'hack',
  'mjml',
  'stan',
  'vala',
  'imba',
  'pypy',
  'self',
  'clio',
  'daml',
  'qore',
  'wasp',
  'sass',
  'less',
  'cjss',
  'ruru',
  'tmux',
  'navi',
  'grpc',
  'rest',
  'tars',
  'jstl',
  'ff4j',
  'jdsp',
  '.net',
  'play',
  'mean',
  'twig',
  'kivy',
  'osgi',
  'iris',
  'aura',
  'mono',
  'axon',
  'volt',
  'jaws',
  'rook',
  'riak',
  'tidb',
  'rxdb',
  'nedb',
  'mapd',
  'crux',
  'noms',
  'dolt',
  'mqtt',
  'xmpp',
  'msmq',
  'rsmq',
  'acho',
  'kdb+',
  'mule',
  'cdap',
  'kylo',
  'zato',
  'mara',
  'bull',
  'ksql',
  'riko',
  'gorm',
  'gino',
  'otrs',
  'kowl',
  'jooq',
  'skor',
  'pome',
  'pyup',
  'chef',
  'salt',
  'mina',
  'juju',
  'blox',
  'snyk',
  'mabl',
  'gocd',
  'dash',
  'zest',
  'jspm',
  'pnpm',
  'wapm',
  'fork',
  'onyx',
  'mamp',
  'warp',
  'mr.2',
  'kong',
  'zuul',
  'dapr',
  'pact',
  'kuma',
  'tars',
  'effx',
  'dchq',
  'maas',
  'gaia',
  'atom',
  'nova',
  'vimr',
  'slap',
  'qemu',
  'kops',
  'otto',
  'gulp',
  'vite',
  'rome',
  'just',
  'maid',
  'etcd',
  'serf',
  'vyne',
  'yarn',
  'ploi',
  'buck',
  'mill',
  'glbc',
  'gvfs',
  'marp',
  'lgtm',
  'ship',
  'deco',
  'zend',
  'kite',
  'spek',
  'helm',
  'argo',
  'xmpp',
  'lens',
  'tilt',
  'ctop',
  'kind',
  'moby',
  'cape',
  'kopf',
  'kctf',
  'rome',
  'hava',
  'ff4j',
  'snyk',
  'reek',
  'fody',
  'jest',
  'chai',
  'dist',
  'pypi',
  'kiwi',
  'gogs',
  'loki',
  'jeli',
  'prtg',
  'dpdk',
  'devo',
  'stts',
  'hund',
  'treo',
  'pixi',
  'ward',
  'orbtk',
  'unity',
  'godot',
  'crown',
  'gnome',
  'netty',
  'tokio',
  'gpars',
  'serde',
  'rekit',
  'uikit',
  'bulma',
  'iview',
  'gumby',
  'udash',
  'linux',
  'macos',
  'nixos',
  'talos',
  'onos-',
  'ionic',
  'felgo',
  'phonk',
  'hazel',
  'vuido',
  'flask',
  'lumen',
  'grape',
  'nancy',
  'silex',
  'kemal',
  'balde',
  'pippo',
  'jinja',
  'jtwig',
  'html5',
  'css 3',
  'swift',
  'scala',
  'julia',
  'ocaml',
  'jruby',
  'cobol',
  'pharo',
  'boost',
  'lucee',
  'grain',
  'mruby',
  'jolie',
  'fstar',
  'canjs',
  'xtend',
  'helix',
  'odata',
  'preql',
  'guava',
  'web3j',
  'jsoup',
  'teavm',
  'rails',
  'actix',
  'vapor',
  'io.js',
  'guice',
  'beego',
  'revel',
  'yesod',
  'nette',
  'blade',
  'jooby',
  'geddy',
  'bolts',
  'minio',
  'storj',
  'ambry',
  'mysql',
  'hbase',
  'mssql',
  'citus',
  'nuodb',
  'iondb',
  'lindb',
  'umbra',
  'kafka',
  'samza',
  'mosca',
  'hutch',
  'datos',
  'myria',
  'jitsu',
  'redis',
  'keydb',
  'mapdb',
  'books',
  'aiven',
  'druid',
  'vespa',
  'runit',
  'workq',
  'realm',
  'heron',
  'faust',
  'samza',
  'neo4j',
  'titan',
  'grakn',
  'ebean',
  'luigi',
  'unito',
  'aiven',
  'slick',
  'sqoop',
  'migra',
  'mycli',
  'prest',
  'dbase',
  'mapdb',
  'pgweb',
  'pgcli',
  'quilt',
  'zheap',
  'fossa',
  'karma',
  'watir',
  'galen',
  'phpci',
  'dotci',
  'theia',
  'codio',
  'buidl',
  'paket',
  'homer',
  'nuget',
  'myget',
  'phing',
  'baget',
  'xrepo',
  'psake',
  'scons',
  'tulsi',
  'coder',
  'magit',
  'pijul',
  'mysos',
  'tower',
  'gitup',
  'vault',
  'scalr',
  'ngrok',
  'gotty',
  'istio',
  'micro',
  'zeebe',
  'hyper',
  'buddy',
  'emacs',
  'gedit',
  'micro',
  'squid',
  'nomad',
  'dc/os',
  'kocho',
  'grunt',
  'sagui',
  'zetcd',
  'bower',
  'percy',
  'cmake',
  'bazel',
  'pants',
  'envoy',
  'pound',
  'fabio',
  'ungit',
  'gitql',
  'gitui',
  'polly',
  'caret',
  'derek',
  'gisto',
  'xcode',
  'clion',
  'pharo',
  'geany',
  'solis',
  'xmake',
  'junit',
  'rspec',
  'xunit',
  'nunit',
  'behat',
  'detox',
  'mockk',
  'pumba',
  'atata',
  'scope',
  'jsdom',
  'tutum',
  'weave',
  'lando',
  'clair',
  'trivy',
  'fleet',
  'furan',
  'k3sup',
  'torus',
  'pixie',
  'cri-o',
  'cycle',
  'draft',
  'smith',
  'titus',
  'otomi',
  'maesh',
  'yocto',
  'atlas',
  'scalr',
  'fugue',
  'babel',
  'fable',
  'split',
  'flagr',
  'petri',
  'flipt',
  'coala',
  'hound',
  'infer',
  'credo',
  'psalm',
  'sider',
  'ktfmt',
  'mocha',
  'qunit',
  'conan',
  'aptly',
  'relay',
  'gitea',
  'deveo',
  'log4j',
  'loggr',
  'kuoll',
  'fyipe',
  'vigil',
  'amixr',
  'beats',
  'snort',
  'slf4j',
  'humio',
  'logmx',
  'dome9',
  'opsee',
  'fyipe',
  'ruxit',
  'scout',
  'falco',
  'qbaka',
  'sensu',
  'cacti',
  'munin',
  'kiali',
  'monit',
  'bosun',
  'cabot',
  'kamon',
  'fyipe',
  'zyxel',
  'cicada',
  'nyagos',
  'runops',
  'phaser',
  'pygame',
  'libgdx',
  'divjoy',
  'nimble',
  'flakes',
  'primer',
  'cirrus',
  'shmenu',
  'ubuntu',
  'debian',
  'centos',
  'fedora',
  'coreos',
  'cygwin',
  'devuan',
  'openfl',
  'j2objc',
  'matcha',
  'donejs',
  'javafx',
  'photon',
  'macgap',
  'openfl',
  'sciter',
  'guzzle',
  'jersey',
  'falcon',
  'bottle',
  'sapper',
  'trails',
  'nameko',
  'pencil',
  'leptus',
  'smarty',
  'liquid',
  'hamlet',
  'dot.js',
  'eta js',
  'askama',
  'python',
  'kotlin',
  'elixir',
  'groovy',
  'erlang',
  'matlab',
  'octave',
  'racket',
  'autoit',
  'pascal',
  'unison',
  'stylus',
  'precss',
  'goober',
  'vue.js',
  'donejs',
  'opencl',
  'strans',
  'cruddl',
  'irisql',
  'baseql',
  'prisma',
  'jsoniq',
  'java 8',
  'rxjava',
  'lombok',
  'javacc',
  'xrebel',
  'wasmer',
  'django',
  'spring',
  'meteor',
  'nestjs',
  'grails',
  'vert.x',
  'vaadin',
  'rocket',
  'kohana',
  'hanami',
  'dancer',
  'web2py',
  'swoole',
  'hoodie',
  'egg.js',
  'escher',
  'vibora',
  'saturn',
  'graphp',
  'icloud',
  'sqlite',
  'hadoop',
  'oracle',
  'scylla',
  'vitess',
  'litedb',
  'alasql',
  'sybase',
  'hsqldb',
  'sqlyog',
  'mentat',
  'exasol',
  'rqlite',
  'tokumx',
  'heroic',
  'badger',
  'zerodb',
  'tokudb',
  'tibero',
  'olegdb',
  'irondb',
  'edgedb',
  'duckdb',
  'torodb',
  'ts-sql',
  'tiledb',
  'celery',
  'zeromq',
  'ibm mq',
  'ironmq',
  'disque',
  'ralley',
  'stitch',
  'dremio',
  'qubole',
  'alooma',
  'census',
  'etleap',
  'memsql',
  'lokijs',
  'voltdb',
  'tile38',
  'buntdb',
  'ncache',
  'griddb',
  'jawsdb',
  'splunk',
  'presto',
  'talend',
  'dremio',
  'singer',
  'aresdb',
  'pilosa',
  'stumpy',
  'corral',
  'stroom',
  'resque',
  'dgraph',
  'cayley',
  'akutan',
  'dapper',
  'peewee',
  'dbflow',
  'notorm',
  'digdag',
  'sococo',
  'couler',
  'lenses',
  'flyway',
  'airpal',
  'sequel',
  'forest',
  'popsql',
  'sqlyog',
  'sqlpad',
  'omnidb',
  'pghero',
  'sqldep',
  'sqitch',
  'pgrita',
  'xmysql',
  'dbngin',
  'dbdocs',
  'pgdash',
  'iredis',
  'pgsync',
  'pugsql',
  'phxsql',
  'fabric',
  'cpanel',
  'webmin',
  'shipit',
  'itamae',
  'pallet',
  'awless',
  'cronyo',
  'testim',
  'autify',
  'qmetry',
  'axcept',
  'airtap',
  'bamboo',
  'hudson',
  'lambci',
  'koding',
  'gitpod',
  'codiad',
  'poetry',
  'anyapi',
  'proget',
  'sdkman',
  'pydist',
  'sorbet',
  'envkey',
  'shutit',
  'expose',
  'webtty',
  'jersey',
  'ocelot',
  'seneca',
  'nameko',
  'cortex',
  'armory',
  'neovim',
  'coda 2',
  'bbedit',
  'remacs',
  '\u03bbiquid',
  'yeoman',
  'nuster',
  'parcel',
  'rollup',
  'brunch',
  'fly.js',
  'harbor',
  'consul',
  'eureka',
  'skydns',
  'dockup',
  'gradle',
  'please',
  'seesaw',
  'katran',
  'inlets',
  'zephyr',
  'qmetry',
  'go-git',
  'getgit',
  'kooder',
  'typora',
  'devhub',
  'astral',
  'gordon',
  'shrink',
  'gitrob',
  'lepton',
  'datree',
  'lmvtfy',
  'cashew',
  'karyon',
  'goland',
  'delphi',
  'spyder',
  'kretes',
  'vundle',
  'ionide',
  'vschat',
  'kooder',
  'pytest',
  'testng',
  'behave',
  'inspec',
  'dbunit',
  'canopy',
  'kotest',
  'kahlan',
  'lippia',
  'waydev',
  'splash',
  'harbor',
  'spread',
  'kaniko',
  'helios',
  'kubedb',
  'okteto',
  'octant',
  'contiv',
  'garden',
  'makisu',
  'velero',
  'kruise',
  'nixery',
  'lagoon',
  'lenses',
  'ofelia',
  'arkade',
  'tandem',
  'packer',
  'pulumi',
  'clutch',
  'hermes',
  'codota',
  'eslint',
  'codacy',
  'tslint',
  'jacoco',
  'pylint',
  'jshint',
  'jslint',
  'cacher',
  'roslyn',
  'datree',
  'ktlint',
  'gitcop',
  'xrebel',
  'embold',
  'enzyme',
  'repman',
  'docker',
  'openvz',
  'zerovm',
  'appium',
  'apptim',
  'cto.ai',
  'sleuth',
  'github',
  'gitlab',
  'sympli',
  'fossil',
  'onedev',
  'bunyan',
  'willow',
  'loggie',
  'sentry',
  'raygun',
  'opbeat',
  'errbit',
  'logify',
  'whatap',
  'splunk',
  'loggly',
  'logdna',
  'scalyr',
  'scribe',
  'ok log',
  'stroom',
  'signl4',
  'lumigo',
  'cachet',
  'raygun',
  'kadira',
  'iopipe',
  'vector',
  'signoz',
  'plumbr',
  'atatus',
  'kibana',
  'nagios',
  'zabbix',
  'statsd',
  'jaeger',
  'icinga',
  'zipkin',
  'sysdig',
  'thanos',
  'ambari',
  'lumigo',
  'alerta',
  'vulcan',
  'whatap',
  'veneur',
  'zenoss',
  'runops',
  'glimmer',
  'ipython',
  'ninject',
  'panda3d',
  'finagle',
  'orleans',
  'primeng',
  'linqpad',
  'shuffle',
  'nuxt.js',
  'vuetify',
  'polymer',
  'vue cli',
  'flat ui',
  'ring ui',
  'toolkit',
  'fluxxor',
  'basscss',
  'new.css',
  'topcoat',
  'axentix',
  'bosonic',
  'windows',
  'freebsd',
  'manjaro',
  'openbsd',
  'freeipa',
  'freenas',
  'kubuntu',
  'tailsos',
  'flutter',
  'xamarin',
  'f-droid',
  'element',
  'nodegui',
  'gallium',
  'sinatra',
  'typeorm',
  'fastify',
  'aiohttp',
  'asyncio',
  'restify',
  'fastapi',
  'javalin',
  'jsonnet',
  'asp.net',
  'clojure',
  'haskell',
  'java ee',
  'rstudio',
  'crystal',
  'geojson',
  'postcss',
  'compass',
  'bourbon',
  'aurelia',
  'mithril',
  'chaplin',
  'gridbox',
  'cursive',
  'picocli',
  'sampler',
  'janetsh',
  'mercury',
  'graphql',
  'jsonapi',
  'jsonata',
  'vulcain',
  'quarkus',
  'mybatis',
  'jackson',
  'ratpack',
  'assertj',
  'jgrapht',
  'activej',
  'lunatic',
  'node.js',
  'asp.net',
  'laravel',
  'symfony',
  'next.js',
  'cakephp',
  'tornado',
  'phalcon',
  'php-mvc',
  'pyramid',
  'twisted',
  'finatra',
  'padrino',
  'fuelphp',
  'draftjs',
  'webapp2',
  'martini',
  'ratpack',
  'redwood',
  'buffalo',
  'meatier',
  'grizzly',
  'vraptor',
  'macaron',
  'diamond',
  'bubbles',
  'jolteon',
  'phpixie',
  'swifton',
  'openebs',
  'rethink',
  'dclouds',
  'mongodb',
  'mariadb',
  'couchdb',
  'ibm db2',
  'pouchdb',
  'percona',
  'rocksdb',
  'vertica',
  'datomic',
  'faunadb',
  'ravendb',
  'leveldb',
  'crateio',
  'monetdb',
  'orbitdb',
  'questdb',
  'unqlite',
  'chronix',
  'ledisdb',
  'traildb',
  'actordb',
  'graphdb',
  'bageldb',
  'gearman',
  'kestrel',
  'vernemq',
  'nanomsg',
  'mediatr',
  'sparrow',
  'compose',
  'xplenty',
  'panoply',
  'airbyte',
  'hotglue',
  'cleardb',
  'tempodb',
  'geniedb',
  'ehcache',
  'vertica',
  'atscale',
  'alation',
  'eventql',
  'grooper',
  'datajet',
  'sidekiq',
  'php-fpm',
  'faktory',
  'mongoid',
  'mybatis',
  'airflow',
  'camunda',
  'zenaton',
  'tallyfy',
  'freeter',
  'wrangle',
  'vchasno',
  'rdkafka',
  'kafkahq',
  'kafdrop',
  'postgis',
  'dbeaver',
  'knex.js',
  'pgadmin',
  'navicat',
  'robo 3t',
  'postico',
  'patroni',
  'psequel',
  'redsmin',
  'sqlgate',
  'stellar',
  'teamsql',
  'postage',
  'fake2db',
  'redisql',
  'litecli',
  'pgtyped',
  'pghoard',
  'odyssey',
  'sqlflow',
  'octosql',
  'massive',
  'xgboost',
  'testify',
  'ansible',
  'rundeck',
  'cleaver',
  'aws cli',
  'vantage',
  'endgame',
  'autofac',
  'doppins',
  'kobiton',
  'endtest',
  'nemo.js',
  'reflect',
  'panther',
  'diffhub',
  'gitduck',
  'jenkins',
  'bitrise',
  'wercker',
  'snap ci',
  'strider',
  'zuul ci',
  'vespene',
  'layerci',
  'codepen',
  'dartpad',
  'codebox',
  'bundler',
  'ninject',
  'devdocs',
  'bump.sh',
  'horizen',
  'pub.dev',
  'dephell',
  'pyright',
  'gitless',
  'navicat',
  'keywhiz',
  'doppler',
  'biscuit',
  'mist.io',
  'termius',
  'linkerd',
  'fabric8',
  'claudia',
  'hexagon',
  'armeria',
  'helidon',
  'dactory',
  'graalvm',
  'bitnami',
  'orchard',
  'codecov',
  'tinymce',
  'rstudio',
  'codepen',
  'kakoune',
  'slushjs',
  'lineman',
  'varnish',
  'section',
  'peloton',
  'vagrant',
  'libvirt',
  'puphpet',
  'webpack',
  'jetpack',
  'stealjs',
  'quay.io',
  'gandalf',
  'bundler',
  'dockbit',
  'jitpack',
  'capsule',
  'haproxy',
  'traefik',
  'hipache',
  'vulcand',
  'hiptest',
  'qase.io',
  'git lfs',
  'lazygit',
  'gitsome',
  'xltrail',
  'gitlint',
  'deepgit',
  'git-bug',
  'git-dit',
  'gitmask',
  'autogit',
  'polygit',
  'hystrix',
  'codekit',
  'prepros',
  'macdown',
  'release',
  'octokit',
  'codehub',
  'octobox',
  'mergify',
  'codenav',
  'deckhub',
  'backhub',
  'gitnews',
  'pycharm',
  'eclipse',
  'rstudio',
  'truffle',
  'appcode',
  'nuclide',
  'materia',
  'lazarus',
  'cursive',
  'carbide',
  'ncrunch',
  'tabnine',
  'tokamak',
  'dendron',
  'fisheye',
  'biicode',
  'phpunit',
  'mockito',
  'phpspec',
  'jbehave',
  'lettuce',
  'testery',
  'mockolo',
  'automqa',
  'equa11y',
  'rancher',
  'autofac',
  'flux cd',
  'gitkube',
  'flocker',
  'kompose',
  'kubespy',
  'habitus',
  'conduit',
  'flagger',
  'kubectx',
  'hyscale',
  'cast.ai',
  'earthly',
  'dotmesh',
  'kubetap',
  'k8guard',
  'railcar',
  'kubenav',
  'dockter',
  'komodor',
  'kubesql',
  'firepad',
  'habitat',
  'metamon',
  'sucrase',
  'quickjs',
  'rollout',
  'airship',
  'mutagen',
  'devskim',
  'rubocop',
  'phpstan',
  'styleci',
  'reshift',
  'piranha',
  'ndepend',
  'cypress',
  'jasmine',
  'sinonjs',
  'gemfury',
  'packagr',
  'smartos',
  'boxfuse',
  'flatpak',
  'bitrise',
  'magneto',
  'kobiton',
  'pcloudy',
  'drydock',
  'updraft',
  'bintray',
  'gitblit',
  'codehub',
  'gitplex',
  'radicle',
  'nanolog',
  'komiser',
  'trackjs',
  'rollbar',
  'bugsnag',
  'overops',
  'epsagon',
  'ncrunch',
  'log owl',
  'pingdom',
  'checkly',
  'panopta',
  'picreel',
  'distill',
  'zenduty',
  'kintaba',
  'riemann',
  'pi-hole',
  'nodemon',
  'nodefly',
  'graylog',
  'fluentd',
  'serilog',
  'logz.io',
  'logback',
  'rsyslog',
  'buglife',
  'cast.ai',
  'opsview',
  'checkup',
  'staytus',
  'datadog',
  'librato',
  'navicat',
  'instana',
  'monitis',
  'thundra',
  'opsdash',
  'checkly',
  'sealion',
  'profilo',
  'grafana',
  'netdata',
  'checkmk',
  'ganglia',
  'shinken',
  'rrdtool',
  'glances',
  'opennms',
  'opsview',
  'skedler',
  'runbook',
  'gunnery',
  'forever',
  'ionicons',
  'feathers',
  'shoelace',
  'jsx lite',
  'gnu bash',
  'nu shell',
  'three.js',
  'monogame',
  'buildbox',
  'amethyst',
  'scramjet',
  'bloomrpc',
  'protobuf',
  'structor',
  'skeleton',
  'mini.css',
  'tachyons',
  'avalonia',
  'suit css',
  'mac os x',
  'opensuse',
  'raspbian',
  'cnvrg.io',
  'mqx rtos',
  'lever os',
  'phonegap',
  'onsen ui',
  'electron',
  'sails.js',
  'loopback',
  'tastypie',
  'aqueduct',
  'total.js',
  'colossus',
  'go-fiber',
  'rapidsms',
  'leaf php',
  'mustache',
  'hogan.js',
  'nunjucks',
  'markdown',
  'gnu bash',
  'reasonml',
  'vbscript',
  'rescript',
  'listmonk',
  'topshell',
  'metacode',
  'acucobol',
  'stitches',
  'compiled',
  'ember.js',
  'durandal',
  'pingendo',
  'scoop.sh',
  'spectaql',
  'firecamp',
  'json-rpc',
  'json api',
  'graphene',
  'querydsl',
  'eventbus',
  'proguard',
  'archunit',
  'jhipster',
  'adonisjs',
  'thinkphp',
  'fat-free',
  'total.js',
  'tapestry',
  'masonite',
  'catalyst',
  'scalatra',
  'purplejs',
  'rapidoid',
  'vulcanjs',
  'portworx',
  'runabove',
  'mcrouter',
  'influxdb',
  'arangodb',
  'firebird',
  'orientdb',
  'opentsdb',
  'kairosdb',
  'altibase',
  'exist-db',
  'harperdb',
  'jsonlite',
  'cakebase',
  'kinetica',
  'apsaradb',
  'rabbitmq',
  'activemq',
  'ejabberd',
  'starling',
  'dramatiq',
  'mongolab',
  'fivetran',
  'ataccama',
  'sap hana',
  'beringei',
  'summitdb',
  'cqengine',
  'vineyard',
  'aws glue',
  'trifacta',
  'mondrian',
  'amundsen',
  'datameer',
  'hangfire',
  'posthook',
  'fireworq',
  'mongoose',
  'greendao',
  'redpanda',
  'humanify',
  'memgraph',
  'coredata',
  'mikroorm',
  'greendao',
  'sql+.net',
  'kissflow',
  'shipyard',
  'cloudapp',
  'chubaofs',
  'kafka ui',
  'cloudant',
  'datagrip',
  'graphiql',
  'heidisql',
  'querydsl',
  'debezium',
  'proxysql',
  'maxscale',
  'strongdm',
  'sql tabs',
  'dataform',
  'basedash',
  'atlas-db',
  'pandasql',
  'dbschema',
  'pgwatch2',
  'querypie',
  'pgloader',
  'pg_flame',
  'dynobase',
  'pgdoctor',
  'plpgunit',
  'adminium',
  'pgrebase',
  'rdbtools',
  'dropbase',
  'octo cli',
  'goconvey',
  'runcloud',
  'cfengine',
  '\u03bb gordon',
  'lambdoku',
  'cloudviz',
  'tidelift',
  'selenium',
  'selenide',
  'ghostlab',
  'usetrace',
  'atompair',
  'circleci',
  'codeship',
  'teamcity',
  'drone.io',
  'appveyor',
  'buildbot',
  'testling',
  'jsfiddle',
  'kobra.io',
  'carthage',
  'devhints',
  'composer',
  'homebrew',
  'rubygems',
  'runnable',
  'dynomite',
  'smartgit',
  'knox-app',
  'akeyless',
  'ibm sklm',
  'morpheus',
  'pagekite',
  'devutils',
  'tunnelto',
  'go micro',
  'pactflow',
  'opslevel',
  'tectonic',
  'uberalls',
  'istanbul',
  'virtkick',
  'opsstack',
  'deployer',
  'cloud 66',
  'deployhq',
  'brackets',
  'textmate',
  'vscodium',
  'org mode',
  'quill.js',
  'gardener',
  'kubevirt',
  'snowpack',
  'backpack',
  'entropic',
  'pika.dev',
  'distelli',
  'eventbus',
  'testrail',
  'testlink',
  'applause',
  'kualitee',
  'git flow',
  'git-repo',
  'gitstats',
  'gitsense',
  'octotree',
  'devspace',
  'gitscout',
  'pull dog',
  'gitpoint',
  'github1s',
  'phpstorm',
  'webstorm',
  'rubymine',
  'codelite',
  'kdevelop',
  'aquameta',
  'atom-ide',
  'vim-plug',
  'spacevim',
  'gitsavvy',
  'github1s',
  'opengrok',
  'metacode',
  'cucumber',
  'capybara',
  'testcafe',
  'specflow',
  'selenide',
  'unittest',
  'fitnesse',
  'typemock',
  'happo.io',
  'howitzer',
  'wakatime',
  'haystack',
  'casperjs',
  'slimerjs',
  'marathon',
  'minikube',
  'skaffold',
  'linuxkit',
  'portworx',
  'hadolint',
  'dockersh',
  'devspace',
  'helmfile',
  'kubecost',
  'cycle.io',
  'oneinfra',
  'gopaddle',
  'openyurt',
  'headlamp',
  'conclave',
  'scala.js',
  'sketchup',
  'diagrams',
  'cloudviz',
  'prettier',
  'crucible',
  'findbugs',
  'veracode',
  'brakeman',
  'codebeat',
  'bithound',
  'gitprime',
  'codenarc',
  'deepscan',
  'codebrag',
  'textlint',
  'stylefmt',
  'codegrip',
  'sourcery',
  'last-hit',
  'baretest',
  'venus.js',
  'fastlane',
  'earlgrey',
  'apperian',
  'perforce',
  'upsource',
  'gitolite',
  'airbrake',
  'elmah.io',
  'site24x7',
  'gtmetrix',
  'oh dear!',
  'alertbot',
  'nodeping',
  'webgazer',
  'monitoro',
  'opsgenie',
  'bigpanda',
  'cronitor',
  'alertops',
  'spike.sh',
  'xmatters',
  'librenms',
  'wireedit',
  'nodetime',
  'logstash',
  'filebeat',
  'logmatic',
  'sematext',
  'logtrail',
  'logagent',
  'gravwell',
  'logit.io',
  'logsense',
  'instabug',
  'autotune',
  'metricly',
  'statusfy',
  'instatus',
  'pagefate',
  'skylight',
  'signalfx',
  'stackify',
  'dashbird',
  'uptrends',
  'boundary',
  'opsmatic',
  'jennifer',
  'checkbot',
  'circonus',
  'metricly',
  'opstrace',
  'graphite',
  'telegraf',
  'collectd',
  'centreon',
  'flapjack',
  'statsite',
  'circonus',
  'searchly',
  'xitoring',
  'elementui',
  'chakra ui',
  'jqwidgets',
  'matestack',
  'cocos2d-x',
  'babylonjs',
  'blend4web',
  'gb studio',
  'vue-model',
  'bootstrap',
  'milligram',
  'water.css',
  'rancheros',
  'stratumos',
  'capacitor',
  'filemaker',
  'crosswalk',
  'fuse open',
  'pepperoni',
  'fabric.io',
  'viroreact',
  'wxwidgets',
  'electrino',
  'expressjs',
  'rails api',
  'moleculer',
  'akka http',
  'starlette',
  'flow (js)',
  'slim lang',
  'ractivejs',
  'emblem.js',
  'oh my zsh',
  'smalltalk',
  'fabric.js',
  'purebasic',
  'node-sass',
  'purifycss',
  'angularjs',
  'angular 2',
  'breeze.js',
  'postsharp',
  'oh my zsh',
  'lip gloss',
  'graphqurl',
  'graphpack',
  'apirocket',
  'thymeleaf',
  'mapstruct',
  'objectify',
  '.net core',
  'gin gonic',
  'richfaces',
  'salesloft',
  'fusion.js',
  'tower web',
  'amazon s3',
  'twemproxy',
  'memcached',
  'cassandra',
  'couchbase',
  'rethinkdb',
  'marklogic',
  'indexeddb',
  'lovefield',
  'objectbox',
  'leanxcale',
  'pumpkindb',
  'transbase',
  'confluent',
  'mosquitto',
  'cloudamqp',
  'amazon mq',
  'sandglass',
  'scalegrid',
  'snowflake',
  'matillion',
  'altiscale',
  'hevo data',
  'hazelcast',
  'aerospike',
  'tarantool',
  'truevault',
  'leanxcale',
  'pachyderm',
  's3-lambda',
  'cloudflow',
  'subserver',
  'taskbotjs',
  'objectbox',
  'confluent',
  'kapacitor',
  'dse graph',
  'hibernate',
  'sequelize',
  'sugar orm',
  'workflowy',
  'workfront',
  'filerobot',
  'restdb.io',
  'liquibase',
  'tableplus',
  'postgrest',
  'studio 3t',
  'pganalyze',
  'vertabelo',
  'graphqurl',
  'pgrouting',
  'objectify',
  'restheart',
  'typegoose',
  'dbdiagram',
  'erbuilder',
  'hackolade',
  'slack sql',
  'trevor.io',
  'datasette',
  'visualops',
  'cisco aci',
  'aws shell',
  'gemnasium',
  'preflight',
  'courgette',
  'travis ci',
  'gitlab ci',
  'concourse',
  'buildkite',
  'semaphore',
  'jenkins x',
  'heroku ci',
  'shippable',
  'solano ci',
  'magnum ci',
  'nevercode',
  'cirrus ci',
  'kraken ci',
  'cumulusci',
  'mottainai',
  'codetasty',
  'cocoapods',
  'cloudrepo',
  'violinist',
  'flow (js)',
  'mercurial',
  'bitkeeper',
  'replicate',
  'gitkraken',
  'torus cli',
  'secrethub',
  'confidant',
  'strongbox',
  'comparium',
  'leancloud',
  'copperegg',
  'cloudbolt',
  'cloudzero',
  'kubestack',
  'requestly',
  'conductor',
  'moleculer',
  'gloo edge',
  'multipass',
  'instainer',
  'coveralls',
  'openstack',
  'spinnaker',
  'deploybot',
  'teletraan',
  'ihp cloud',
  'autorabit',
  'notepad++',
  'ultraedit',
  'coteditor',
  'textadept',
  'parallels',
  'virtuozzo',
  'xenserver',
  'webpacker',
  'system.js',
  'pingy cli',
  'pika pack',
  'zookeeper',
  'requirejs',
  'component',
  'verdaccio',
  'requestly',
  'f5 big-ip',
  'testlodge',
  'webtestit',
  'gitential',
  'git-sizer',
  'gitqlient',
  'gititback',
  'repo-peek',
  'scala ide',
  'codetasty',
  'deepforge',
  'ap studio',
  'shiftedit',
  'spacemacs',
  'resharper',
  'postsharp',
  'neobundle',
  'vuln cost',
  'codeswing',
  'repo-peek',
  'scalatest',
  'testsigma',
  'codealike',
  'phantomjs',
  'puppeteer',
  'portainer',
  'rancheros',
  'kitematic',
  'codefresh',
  'kustomize',
  'centurion',
  'dumb-init',
  'gockerize',
  'kubevault',
  'cloudflow',
  'kubestack',
  'kubestone',
  'crashcart',
  'terraform',
  'buildroot',
  'stacker 1',
  'autocloud',
  'modernizr',
  'configcat',
  'sonarqube',
  'stylelint',
  'sonarlint',
  'scss-lint',
  'swiftlint',
  'sass lint',
  'phacility',
  'gitcolony',
  'supertest',
  'vorlon.js',
  'courgette',
  'packagist',
  'cloudrepo',
  'studio 3t',
  'codemagic',
  'distiller',
  'appcircle',
  'hockeyapp',
  'testfairy',
  'bitbucket',
  'beanstalk',
  'gitbucket',
  'rhodecode',
  'kallithea',
  'gitorious',
  'codeplane',
  'logdevice',
  'cloudbolt',
  'stackhawk',
  'backtrace',
  'glitchtip',
  'errorship',
  'updown.io',
  'freshping',
  'apex ping',
  'pingbreak',
  'hyperping',
  'pagerduty',
  'victorops',
  'squadcast',
  'wireshark',
  'nagios xi',
  'observium',
  'cisco ise',
  'tailscale',
  'forescout',
  'timber.io',
  'sumologic',
  'coralogix',
  'bugfender',
  'bindplane',
  'statusbot',
  'infracost',
  'status.io',
  'statushub',
  'statuspal',
  'new relic',
  'dynatrace',
  'appsignal',
  'aws x-ray',
  'honeycomb',
  'wavefront',
  'lightstep',
  'traceview',
  'netuitive',
  'inspeqtor',
  'rorvswild',
  'pyroscope',
  'fabric.js',
  'sumologic',
  'appoptics',
  'monitorix',
  'monitoror',
  'blueflood',
  'newspoint',
  'storm.dev',
  'ant design',
  'devextreme',
  'telerik ui',
  'mobiscroll',
  'oracle jet',
  'powershell',
  'fish shell',
  'playcanvas',
  'gamesparks',
  'corona sdk',
  'steamworks',
  'codecks.io',
  'appgamekit',
  'protoactor',
  'reactotron',
  'foundation',
  'primefaces',
  'gentelella',
  'reactstrap',
  'bootsfaces',
  'swiftwebui',
  'systemflow',
  'charts.css',
  'android os',
  'arch linux',
  'windows 10',
  'linux mint',
  'kali linux',
  'cloudlinux',
  'void linux',
  'framework7',
  'vue native',
  'nativebase',
  'rubymotion',
  'gamesparks',
  'shoutem ui',
  'trigger.io',
  'manifoldjs',
  'mobiscroll',
  'apportable',
  'juniversal',
  'dropsource',
  'magenative',
  'nativefier',
  'ultralight',
  'neutronium',
  'feathersjs',
  'actionhero',
  'strongloop',
  'propel orm',
  'typescript',
  'purescript',
  'javascript',
  'r language',
  'powershell',
  'processing',
  'rapidminer',
  'livescript',
  'moonscript',
  'marionette',
  'bootswatch',
  'ascii tree',
  'vulcannext',
  'graphql.js',
  'leakcanary',
  'immutables',
  'javamelody',
  'spring mvc',
  'dropwizard',
  'atmosphere',
  'turbogears',
  'jboss seam',
  'sane stack',
  'reactiveui',
  'websharper',
  'bedrock.io',
  'amazon ebs',
  'tardigrade',
  'postgresql',
  'clickhouse',
  'yugabytedb',
  'bigchaindb',
  'symas lmdb',
  'pipelinedb',
  'clustrixdb',
  'velocitydb',
  'databunker',
  'euclidesdb',
  'amazon sqs',
  'streamsets',
  'simplehttp',
  'amazon emr',
  'redisgreen',
  'iris couch',
  'datascript',
  'amazon rds',
  'dimensigon',
  'memcachier',
  'graphenedb',
  'delta lake',
  'streamsets',
  'openrefine',
  'blazingsql',
  'beanstalkd',
  'janusgraph',
  'redisgraph',
  'blazegraph',
  'terminusdb',
  'sqlalchemy',
  'doctrine 2',
  'nhibernate',
  'propel orm',
  'jugglingdb',
  'amazon efs',
  'kattlo cli',
  'cloudboost',
  'velocitydb',
  'sequel pro',
  'phpmyadmin',
  'railsadmin',
  'pipelinedb',
  'bedquiltdb',
  'typearango',
  'fastonosql',
  'lettuce.io',
  'capistrano',
  'easyengine',
  'serverspec',
  'slickstack',
  'cloudslang',
  'scriptrock',
  'localstack',
  'dependabot',
  'guardrails',
  'lambdatest',
  'sauce labs',
  'playwright',
  'wallaby.js',
  'testingbot',
  'blue ocean',
  'quickbuild',
  'githost ci',
  'cloud9 ide',
  'nitrous.io',
  'stackblitz',
  'codeonline',
  'judge0 ide',
  'dependaroo',
  'chocolatey',
  'codepicnic',
  'typescript',
  'git reflow',
  'sourcetree',
  'opennebula',
  'rightscale',
  'commandeer',
  'cloudstick',
  'prosperops',
  'shellvault',
  'packetriot',
  'expressive',
  'gubernator',
  'amazon eks',
  'supergiant',
  'opennebula',
  'eucalyptus',
  'harness.io',
  'codemirror',
  'coderunner',
  'virtualbox',
  'proxmox ve',
  'mesosphere',
  'amazon ecr',
  'keepalived',
  'smartstack',
  'browserify',
  'elasticbox',
  'launchdeck',
  'applitools',
  'lightproxy',
  'apache ant',
  'practitest',
  'root cause',
  'pre-commit',
  'livereload',
  'remarkable',
  'github cli',
  'remergr.io',
  'gitmonitor',
  'apache cxf',
  'platformio',
  'qt creator',
  'komodo ide',
  'continuous',
  'leo editor',
  'querystorm',
  'vscode dms',
  'karate dsl',
  'arquillian',
  'experitest',
  'playwright',
  'chromeless',
  'kubernetes',
  'docker hub',
  'containerd',
  'lazydocker',
  'watchtower',
  'dockerized',
  'gatekeeper',
  'dockerslim',
  'kube-bench',
  'hypernetes',
  'goldpinger',
  'micronetes',
  'avatar-cli',
  'powerstrip',
  'faas-netes',
  'xlskubectl',
  'k8s-mirror',
  'arvancloud',
  'aws proton',
  'emscripten',
  'cloudcraft',
  'cloudockit',
  'codestream',
  'checkstyle',
  'black duck',
  'reviewable',
  'pvs-studio',
  'pullreview',
  'protractor',
  'codeceptjs',
  'buddybuild',
  'greenhouse',
  'experitest',
  'testflight',
  'releasable',
  'codebasehq',
  'crossplane',
  'leakcanary',
  'statuscake',
  'uptime.com',
  'pingometer',
  'stillalive',
  'packetbeat',
  'cloudradar',
  'papertrail',
  'logentries',
  'sumo logic',
  'phppgadmin',
  'changefeed',
  'aws config',
  'stashboard',
  'phpmyadmin',
  'keymetrics',
  'opencensus',
  'speedcurve',
  'prometheus',
  'solarwinds',
  'metricbeat',
  'chronograf',
  'elastalert',
  'opencensus',
  'assertible',
  'terraboard',
  'stackstorm',
  'neptune.io',
  'material-ui',
  'open iconic',
  'headless ui',
  'supabase ui',
  'highland.js',
  'messagepack',
  'react proto',
  'react sight',
  'laravel kit',
  'animate.css',
  'material-ui',
  'semantic ui',
  'materialize',
  'pattern lab',
  'flexible.gs',
  'simple grid',
  'spectre.css',
  'ionic react',
  'apache flex',
  'voltbuilder',
  'objective-c',
  'common lisp',
  'webassembly',
  'go ethereum',
  'asciidoctor',
  'classic asp',
  'hyperscript',
  'animate.css',
  'css modules',
  'backbone.js',
  'espresso.js',
  'tortoisesvn',
  'bash-my-aws',
  'graffiti.js',
  'android sdk',
  'spring boot',
  'codeigniter',
  'mojolicious',
  'angulardart',
  'trailblazer',
  'bear.sunday',
  'scraper api',
  'timescaledb',
  'cockroachdb',
  'h2 database',
  'event store',
  'informatica',
  'amazon qldb',
  'mishmash io',
  'apache nifi',
  'nservicebus',
  'masstransit',
  'mqtt broker',
  'redis cloud',
  'redis to go',
  'elephantsql',
  'graph story',
  'apache hive',
  'apache kudu',
  'delayed_job',
  'apache nifi',
  'recallgraph',
  'apache beam',
  'doctorkafka',
  'kafkacenter',
  'orchestrate',
  'spring data',
  'mysql_utils',
  'postgres.js',
  'upmin admin',
  'dataspeeder',
  'puppet labs',
  'serverpilot',
  'puppet bolt',
  'centmin mod',
  'aws amplify',
  'troposphere',
  'bash-my-aws',
  'bellerophon',
  'greenkeeper',
  'whitesource',
  'webdriverio',
  'browserling',
  'browserbite',
  'test studio',
  'convergence',
  'screwdriver',
  'buildmaster',
  'continua ci',
  'hercules ci',
  'codesandbox',
  'eclipse che',
  'dumber gist',
  'asciidoctor',
  'go packages',
  'plastic scm',
  'commando.io',
  'cloudportam',
  'teleconsole',
  'netflix oss',
  'openvswitch',
  'aws fargate',
  'containerum',
  'deployplace',
  'light table',
  'vmware vsan',
  'yarn hadoop',
  'boot2docker',
  'microbundle',
  'featurepeek',
  'testcaselab',
  'tortoisegit',
  'committasks',
  'browsersync',
  'gitnotifier',
  'travisbuddy',
  'git history',
  'pullapprove',
  'pullpreview',
  'github surf',
  'arduino ide',
  'monodevelop',
  'light table',
  'rest client',
  'github surf',
  'sourcegraph',
  'codeception',
  'robolectric',
  'poltergeist',
  'google test',
  'test studio',
  'recheck-web',
  'squadlytics',
  'netflix oss',
  'aws copilot',
  'kubeadm-aws',
  'kube-hunter',
  'konstellate',
  'kubeadvisor',
  'docker2saas',
  'geoengineer',
  'goformation',
  'cloudmapper',
  'gitguardian',
  'phabricator',
  'scrutinizer',
  'standard js',
  'pullrequest',
  'sourcelevel',
  'sourcetrail',
  'refactor.io',
  'boardingbot',
  'azure repos',
  'tortoisesvn',
  'castle core',
  'cloudmarker',
  'honeybadger',
  'app enlight',
  'uptimerobot',
  'speedfactor',
  'firehydrant',
  'freshstatus',
  'perfops cli',
  'alert logic',
  'chaossearch',
  'streamstash',
  'crashlytics',
  'crittercism',
  'stackdriver',
  'cloudcheckr',
  'statusgator',
  'statusentry',
  'status list',
  'appdynamics',
  'vividcortex',
  'packtracker',
  'cloudprobes',
  'supervisord',
  'opentracing',
  'status list',
  'routine ops',
  'supervisord',
  'md bootstrap',
  'blade ui kit',
  'mat-ui-icons',
  'laravel nova',
  'react cosmos',
  'tailwind css',
  'material kit',
  'alpine linux',
  'amazon linux',
  'oracle linux',
  'linux kernel',
  'gentoo linux',
  'linuxconsole',
  'copperheados',
  'react native',
  'nativescript',
  'sencha touch',
  'codename one',
  'lambdanative',
  'electron.net',
  'uno platform',
  'apache sling',
  'simplify.web',
  'coffeescript',
  'visual basic',
  'actionscript',
  'scala native',
  'autoprefixer',
  'css scan pro',
  'ampersand.js',
  'graphql-yoga',
  'graphql mesh',
  'apache dubbo',
  'postgraphile',
  'graphql ruby',
  'objectivesql',
  'asp.net core',
  'spring batch',
  'api platform',
  'cocoa (os x)',
  'servicestack',
  'asp.net zero',
  'apache dubbo',
  'apache sling',
  'foundationdb',
  'ibm informix',
  'apache derby',
  'watermelondb',
  'dalmatinerdb',
  'kyoto tycoon',
  'node-json-db',
  'cloudkarafka',
  'objectrocket',
  'heroku redis',
  'lambda store',
  'apache spark',
  'apache flink',
  'apache kylin',
  'apache storm',
  'graph engine',
  'nebula graph',
  'simple graph',
  'objection.js',
  'bookshelf.js',
  'objectivesql',
  'apache oozie',
  'kafka sprout',
  'android room',
  'active admin',
  'apache drill',
  'administrate',
  'nosqlbooster',
  'dbvisualizer',
  'orchestrator',
  'humongous.io',
  'objectrocket',
  'foxx-builder',
  'squirrel sql',
  'pg_timetable',
  'aws opsworks',
  's3_disk_util',
  'browserstack',
  'nightwatchjs',
  'testcomplete',
  'test kitchen',
  'finalbuilder',
  'codeanywhere',
  'finalbuilder',
  'coffeescript',
  'vault on aws',
  'sitespeed.io',
  'siteanalyzer',
  'webhookrelay',
  'aws app mesh',
  'foxx-builder',
  'backstage.io',
  'docker cloud',
  'sublime text',
  'highlight.js',
  'apache mesos',
  'libraries.io',
  'baker street',
  'responsively',
  'apache maven',
  'flexbalancer',
  'reportportal',
  'rails spring',
  'working copy',
  'check it out',
  'github polls',
  'next release',
  'netbeans ide',
  'pathogen.vim',
  'testcomplete',
  'knapsack pro',
  'docker swarm',
  'spring cloud',
  'apache dubbo',
  'devops stack',
  'last.backend',
  'powerfulseal',
  'launchdarkly',
  'bullet train',
  'azure devops',
  'code climate',
  'editorconfig',
  'review board',
  'git-appraise',
  'code spotter',
  'code compare',
  'majestic gui',
  'swiftybeaver',
  'nutanix beam',
  'errorception',
  'websitepulse',
  'apache flume',
  'cloudability',
  'chronosphere',
  'statusticker',
  'splunk cloud',
  'blackfire.io',
  'logicmonitor',
  'instrumental',
  'chronosphere',
  'blue matador',
  'react rainbow',
  'xen orchestra',
  'react toolbox',
  'zsh (z shell)',
  'unreal engine',
  'apache thrift',
  'react monocle',
  'react toolbox',
  'bootstrap vue',
  'mozilla brick',
  'elementary os',
  'xamarin forms',
  'proton native',
  'react desktop',
  'handlebars.js',
  'jade language',
  'clojurescript',
  'zsh (z shell)',
  'jetbrains mps',
  'object pascal',
  'katana-parser',
  'shards ui kit',
  'graphql nexus',
  'graphql faker',
  'async-graphql',
  'slash graphql',
  'oracle pl/sql',
  'apache xerces',
  'apache wicket',
  'apache struts',
  'yew framework',
  'apache cocoon',
  'cuba platform',
  'azure storage',
  'oracle pl/sql',
  'apache pulsar',
  'scheduler api',
  'mongodb atlas',
  'azure synapse',
  'treasure data',
  'pelikan cache',
  'apache ignite',
  'amazon aurora',
  'planetscaledb',
  'database labs',
  'tigergraph db',
  'graphql cache',
  'amazon athena',
  'apache impala',
  'azure synapse',
  'redux persist',
  'kafka streams',
  'kafka manager',
  'datomic cloud',
  'reactivemongo',
  'sqlpro studio',
  'scalablespace',
  'rainforest qa',
  'aws codebuild',
  'sublime merge',
  'arangodb foxx',
  'joyent triton',
  'containership',
  'monaco editor',
  'vmware fusion',
  'apache aurora',
  'xen orchestra',
  'metro bundler',
  'open-registry',
  'laravel forge',
  'diff so fancy',
  'git-fastclone',
  'rebase-editor',
  'git-workspace',
  'github native',
  'vim-repo-edit',
  'visual studio',
  'intellij idea',
  'aptana studio',
  'rust-analyzer',
  'vim-repo-edit',
  'hound by etsy',
  'rancher fleet',
  'kubectl flame',
  'graphite docs',
  'codefactor.io',
  'coverity scan',
  'golangci-lint',
  'sorry-cypress',
  'vagrant cloud',
  'apache allura',
  'cornerstone 4',
  'exceptionless',
  'exceptiontrap',
  'better uptime',
  'opmanager msp',
  'fortianalyzer',
  'sqs-s3-logger',
  'cloudforecast',
  'statuspage.io',
  'nginx amplify',
  'azure monitor',
  'opentelemetry',
  'hostedmetrics',
  'react spectrum',
  'laravel breeze',
  'web components',
  'windows server',
  'oracle solaris',
  'apache cordova',
  'chicken scheme',
  'dhall language',
  'altair graphql',
  'graphql editor',
  'zend framework',
  'react on rails',
  'abp commercial',
  'lift framework',
  'apache calcite',
  'stimulusreflex',
  'flow framework',
  'object storage',
  'apache parquet',
  'galera cluster',
  'distributedlog',
  'pg-amqp-bridge',
  'crunchy bridge',
  'amazon neptune',
  'apache parquet',
  'amazon appflow',
  'github actions',
  'process street',
  'imixs-workflow',
  'datastax astra',
  'galera cluster',
  'database rider',
  'aws cloudshell',
  'katalon studio',
  'ranorex studio',
  'github actions',
  'cake (c# make)',
  'isomorphic-git',
  'galera cluster',
  'docker secrets',
  'docker for aws',
  'ibm containers',
  'vmware vsphere',
  'laravel elixir',
  'kraken by uber',
  'browserify-cdn',
  'octopus deploy',
  'aws codedeploy',
  'sonatype nexus',
  'git extensions',
  'refined github',
  'android studio',
  'vim python ide',
  'wing pythonide',
  'docker compose',
  'docker machine',
  'testcontainers',
  'castle windsor',
  'katacontainers',
  'falco security',
  'devspace cloud',
  'critical stack',
  'unleash hosted',
  'detect-secrets',
  'spring tools 4',
  'quantifiedcode',
  'code inspector',
  'aws codecommit',
  'visualobserver',
  'solarwinds npm',
  'solarwinds nta',
  'aws cloudtrail',
  'server density',
  'catchpoint rum',
  'solarwinds ncm',
  'react storybook',
  'laravel voyager',
  'material design',
  'amazon freertos',
  'web starter kit',
  'electron fiddle',
  'spark framework',
  'bosque language',
  'tailwindcss jit',
  'bootstrap.build',
  'graphql voyager',
  'juniper graphql',
  'project reactor',
  'nette framework',
  'django channels',
  'hydra framework',
  'amber framework',
  'openstack swift',
  'apache rocketmq',
  'amazon redshift',
  'google bigquery',
  'azure hdinsight',
  'memcached cloud',
  'heroku postgres',
  'azure hdinsight',
  'ibm db2 big sql',
  'graphile worker',
  'amazon dynamodb',
  'cloud firestore',
  'azure cosmos db',
  'amazon simpledb',
  'mysql workbench',
  'mongodb compass',
  'azuredatastudio',
  'laravel prequel',
  'pg_stat_monitor',
  'ghost inspector',
  'azure pipelines',
  'express gateway',
  'lagom framework',
  'weaveworks flux',
  'codelobster ide',
  'ottomatica slim',
  'chrome devtools',
  'ghost inspector',
  'simply testable',
  'node-http-proxy',
  'atlassian stash',
  'github notifier',
  'jetbrains rider',
  'jetbrains space',
  'haskell for mac',
  'codelobster ide',
  'chat for vscode',
  'robot framework',
  'spock framework',
  'headlesstesting',
  'microcontainers',
  'simple injector',
  'roboll helmfile',
  'swiss army kube',
  'benchmarkdotnet',
  'amazon codeguru',
  'php codesniffer',
  'better code hub',
  'ghost inspector',
  'packagecloud.io',
  'cocoalumberjack',
  'request metrics',
  'healthchecks.io',
  'timberio vector',
  'statusdashboard',
  'request metrics',
  'hosted graphite',
  'bootstrap styled',
  'radix primitives',
  'redux observable',
  'quasar framework',
  'bootstrap styled',
  'wind river linux',
  'nativescript-vue',
  'electron toolkit',
  'bootstrap studio',
  'spring framework',
  'dframe framework',
  'microsoft access',
  'google cloud sql',
  'entity framework',
  'beekeeper studio',
  'valentina studio',
  'idera sql secure',
  'instance watcher',
  'svn (subversion)',
  'thundra sidekick',
  'aws codepipeline',
  'urbancode deploy',
  'oracle vm server',
  'qtest management',
  'grape for github',
  'adobe coldfusion',
  'debug visualizer',
  'nimble framework',
  'play with docker',
  'cluster turndown',
  'closure compiler',
  'sparkleformation',
  'review assistant',
  'aws codeartifact',
  'clear containers',
  'fluentvalidation',
  'netflix dispatch',
  'cisco dna center',
  'nodejs-dashboard',
  'amazon guardduty',
  'monitor in a box',
  'material tailwind',
  'react-three-fiber',
  'felgo game engine',
  'amazon lumberyard',
  'angular universal',
  'react native seed',
  'graphql inspector',
  'apache freemarker',
  'phoenix framework',
  'cocoa touch (ios)',
  'amazon timestream',
  'openlink virtuoso',
  'azure service bus',
  'azure redis cache',
  'amazon documentdb',
  'ansible semaphore',
  'aws audit manager',
  'teletype for atom',
  'ibm swift sandbox',
  'components.studio',
  'laravel homestead',
  'docker datacenter',
  'apache cloudstack',
  'adobe dreamweaver',
  'boxer text editor',
  'parallels desktop',
  'jfrog artifactory',
  'fluent assertions',
  'seleniumaxedotnet',
  'serverless chrome',
  'kubernetes-deploy',
  'aws app2container',
  'container factory',
  'amazon eks distro',
  'google cloud code',
  'fabric by twitter',
  'github enterprise',
  'jfrog artifactory',
  'sendquick oncloud',
  'splunk enterprise',
  'amazon cloudwatch',
  'apache skywalking',
  'network polygraph',
  'laravel telescope',
  'pa server monitor',
  'gamemaker studio 2',
  'sauron (framework)',
  'open network linux',
  'microsoft power fx',
  'serverless appsync',
  'picturesafe-search',
  'react on rails pro',
  'hpe nimble storage',
  'azure sql database',
  'greenplum database',
  'hosted mqtt server',
  'azure sql database',
  'cloud db for mysql',
  'amazon elasticache',
  'paas db postgresql',
  'azure data factory',
  'realm react native',
  'graphql playground',
  'percona xtrabackup',
  'postgresql modeler',
  'kube-secret-syncer',
  'google cloud build',
  'hashicorp waypoint',
  'visual studio code',
  'pre-commit by yelp',
  'compass for github',
  'bitnami stacksmith',
  'aws cloudformation',
  'hashicorp sentinel',
  'gerrit code review',
  'cloudsmith package',
  'hosted status page',
  'dropwizard metrics',
  'netflix flamescope',
  'ruby server timing',
  'material-ui builder',
  'foundation for apps',
  'solid design system',
  'micronaut framework',
  'qcobjects framework',
  'digitalocean spaces',
  'cloud local storage',
  'cloudera enterprise',
  'stratio datacentric',
  'datastax enterprise',
  'crossbrowsertesting',
  'bitbucket pipelines',
  'aws secrets manager',
  'optimizely rollouts',
  'azure devops server',
  'deepsource analyzer',
  'toad devops toolkit',
  'beta by crashlytics',
  'access point nanohd',
  'material design lite',
  'tailwind starter kit',
  'react native desktop',
  'google cloud storage',
  'microsoft sql server',
  'perconaxtradbcluster',
  'google cloud spanner',
  'lucidlink filespaces',
  'perconaxtradbcluster',
  'dbforge sql complete',
  'master data services',
  'paizacloud cloud ide',
  'azure service fabric',
  'elastic apache mesos',
  'vs code theme studio',
  'sanic for kubernetes',
  'k8s-sidecar-injector',
  'awesometechstack.com',
  'manageengine oputils',
  'statuspage generator',
  'manageengine oputils',
  'clarity design system',
  'microsoft fast design',
  'reactnativeeverywhere',
  'django rest framework',
  'django rest framework',
  'fullstack boilerplate',
  'rackspace cloud files',
  'cloud storage manager',
  'google cloud dataproc',
  'entity framework core',
  'google cloud bigtable',
  'mongodb cloud manager',
  'vmware vcenter server',
  'mongodb cloud manager',
  'apache traffic server',
  'insight.io for github',
  'visual studio for mac',
  'react-testing-library',
  'compose on kubernetes',
  'optimizely full stack',
  'catchpoint synthetics',
  'material components...',
  'lightning web compo...',
  'material design for...',
  'material design for...',
  'lightning web compo...',
  'red hat enterprise ...',
  'visual studio app c...',
  'create react native...',
  'v programming language',
  'starship (shell pro...',
  'graphql query gener...',
  'zen rails base appl...',
  'backblaze b2 cloud ...',
  'digitalocean block ...',
  'percona server for ...',
  'percona server for ...',
  'intersystems iris d...',
  'centralized mtibu d...',
  'apache kafka on heroku',
  'amazon managed stre...',
  'dattell managed str...',
  'data warehouses by ...',
  'google cloud memory...',
  'digitalocean manage...',
  'azure database for ...',
  'azure sql managed i...',
  'rackspace cloud dat...',
  'amazon rds for post...',
  'google cloud sql fo...',
  'azure database for ...',
  'amazon redshift spe...',
  'google cloud data f...',
  'amazon workspaces s...',
  'microsoft power aut...',
  'otrs community edition',
  'amazon managed work...',
  'google cloud filestore',
  'amazon managed apac...',
  'google cloud datastore',
  'firebase realtime d...',
  'microsoft sql serve...',
  'open postgresql mon...',
  'dbforge studio for ...',
  'percona monitoring ...',
  'oracle enterprise m...',
  'aws database migrat...',
  'dbforge studio for ...',
  'mysql performance a...',
  'postgresql for visu...',
  'dbforge studio for ...',
  'devops automation f...',
  'dbforge compare bun...',
  'dbforge query build...',
  'dbforge studio for ...',
  'dbforge documenter ...',
  'dbforge fusion for ...',
  'dbforge data compar...',
  'dbforge compare bun...',
  'dbforge data compar...',
  'dbforge data genera...',
  'dbforge query build...',
  'dbforge schema comp...',
  'dbforge compare bun...',
  'dbforge transaction...',
  'dbforge documenter ...',
  'dbforge schema comp...',
  'sequeltools session...',
  'sql compliance manager',
  'dbforge unit test f...',
  'dbforge index manag...',
  'dbforge monitor for...',
  'dbforge search for ...',
  'dbforge sql decrypt...',
  'data compare for or...',
  'data generator for ...',
  'percona backup for ...',
  'visual studio live ...',
  'visual studio app c...',
  'amazon sagemaker pi...',
  'red hat codeready w...',
  '1password secrets a...',
  'websitepulse test t...',
  'azure app service plan',
  'hhvm (hiphop virtua...',
  'azure virtual machines',
  'amazon ec2 containe...',
  'google kubernetes e...',
  'azure kubernetes se...',
  'azure container ser...',
  'azure container ins...',
  'platform9 managed k...',
  'platform9 managed o...',
  'continuous delivery...',
  'amazon elastic cont...',
  'aws elastic load ba...',
  'digitalocean load b...',
  'google cloud load b...',
  'github load balance...',
  'google traffic dire...',
  'grv - git repositor...',
  'bookmarking for github',
  'red hat codeready s...',
  'slack theme for vscode',
  'google cloud contai...',
  'docker swarm visual...',
  'devspace for kubern...',
  'nvidia container to...',
  'docker immutable wo...',
  'kubernetes-common-s...',
  'aws controllers for...',
  'amazon managed serv...',
  'swiss army kube for...',
  'aws cloud developme...',
  'google cloud deploy...',
  'azure resource manager',
  'dbforge fusion for ...',
  'dbforge fusion for ...',
  'ozcode visual studi...',
  'velocity by code cl...',
  'devops automation f...',
  'apexsql devops toolkit',
  'compliant database ...',
  'google cloud source...',
  'manageengine opmanager',
  'manageengine firewa...',
  'manageengine netflo...',
  'manageengine eventl...',
  'digitalocean monito...',
  'aws cost anomaly de...',
  'decentralized statu...',
  'azure application i...',
  'manageengine applic...',
  'amazon managed serv...',
  'manageengine networ...',
];
export default techStacks;
