spring:
  datasource:
    url: jdbc:mysql://localhost:3306/matching?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true&MVCC=TRUE
    username: root
    password: ssafy

  jpa:
    hibernate:
      naming:
#        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
#    properties:
#      hibernate:
#        show_sql: true # JPA, 하이버네이트가 생성하는 SQL이 로그에 생성 (sysout)
#        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug # JPA, 하이버네이트가 생성하는 SQL이 로그에 생성 (logger)
    org.hibernate.type: trace # 쿼리파라미터 로그